baseURL = 'https://research.testscience.org/'
languageCode = 'en-us'
title = 'Test Science Research Document Library'
theme = ["PaperMod"]
enableInlineShortcodes = true
ShowBreadCrumbs = true
copyright = "[© Institute for Defense Analyses](https://www.ida.org)"


[params]
        defaultTheme = 'light'
        disableThemeToggle = true
        disableScrollToTop = false
        ShowRssButtonInSectionTermList = true
        ShowShareButtons = true
        ShowFullTextinRSS = true
        hideMeta = false
        dateFormat = '2006'
        [params.label]
        icon = "/testsci-logo.png"
        text = "Research Document Library"
        [params.homeInfoParams]
        title = "Welcome!"
        content = "The Test Science Research Document Library comprises methodological developments, lessons learned, and training materials created with a mission to advance the theory and practice of rigorous operational and live fire test and evaluation."

[pagination]
        pagerSize = 1000 # no pagination

[taxonomies]
        year = 'year'
        area = 'areas'
        keyword = 'keywords'
        researchers = 'researchers'
        audience = 'audience'
        venue = 'venues'

# This is needed for Search page
[outputs]
        home = [ "HTML", "RSS", "JSON" ]


[[menu.main]]
         name = "Core Research Areas"
         url = "/areas/"

[[menu.main]]
          name = "Keywords"
          url = "/keywords/"

[[menu.main]]
          name = "Team"
          url = "/researchers/"

[[menu.main]]
          name = "Publication Year"
          url = "/year/"

[[menu.main]]
         name = "Audience"
         url = "/audience/"

[[menu.main]]
        name = "Venue"
        url = "/venues/"

[[menu.main]]
          name = "Search"
          url = "/search/"
          weight = 1
