baseURL = ''
languageCode = 'en-us'
title = 'Test Science Documents Library'
theme = ["PaperMod"]
enableInlineShortcodes = true
ShowBreadCrumbs = true


[params]
        ShowShareButtons = false
        ShowFullTextinRSS = true
        hideMeta = false
        dateFormat = '2006' # You just put a placeholder in to make it only show the year of publication.

[pagination]
        pagerSize = 1000

[params.homeInfoParams]
        Title = "Welcome to the Test Science Document Library!📈"
        Content = "This library comprises all publically available Test Science research papers, slide decks, and presentations.  Publications contain methodological developments, lessons learned, and training materials conducted to advance the theory and practice of rigorous operational and live fire test and evaluation. The library features research conducted with the core Test Science research areas:  Human Systems Interactions, Design of Experiments, Uncertainty Quantification, Reliability Test Planning, Modeling and Simulation Validation, Artificial Intelligence and Autonomy, and Data Management. We hope this resource is a valuable compendium for the test and evaluation community. Contact John Haman for more information."

# TODOs
# Add featured images to each post

[taxonomies]
        year = 'year'
        area = 'areas'
        keyword = 'keywords'
        researchers = 'researchers'
        audience = 'audience'
        venue = 'venues'

# This is needed for Search page
[outputs]
        home = [ "HTML", "RSS", "JSON" ]


[[menu.main]]
         name = "Core Research Areas"
         url = "/areas/"

[[menu.main]]
          name = "Keywords"
          url = "/keywords/"

[[menu.main]]
          name = "Team"
          url = "/researchers/"

[[menu.main]]
          name = "Publication Year"
          url = "/year/"

[[menu.main]]
         name = "Audience"
         url = "/audience/"

[[menu.main]]
        name = "Venue"
        url = "/venues/"

[[menu.main]]
          name = "Search"
          url = "/search/"
          weight = 1
